import { AppLayout } from "@/components/layouts/AppLayout";
import Head from "next/head";
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Datafish v0.0.1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen w-screen">
        <h1>Accueil</h1>
      </div>
    </>
  );
}
