/* eslint-disable react/no-unescaped-entities */
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Datafish v0.0.1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="">
        <h1 className="title">Bienvenue sur Datafish</h1>

        <div className="divider-solid w-1/3 m-2"></div>

        <p className=" md:w-2/3 lg:w-2/4">
          [L'ambition de ce projet est double. D'une part, il vise à éduquer et
          sensibiliser le grand public, les étudiants, les chercheurs et les
          décideurs politiques à la richesse et à la fragilité de la faune
          aquatique. D'autre part, il souhaite fournir un outil précieux aux
          scientifiques et aux conservationnistes pour mieux comprendre et
          protéger ces écosystèmes vitaux.En combinant rigueur scientifique et
          technologies de pointe, nous espérons contribuer à un futur où
          l'information sur la faune aquatique est non seulement accessible,
          mais aussi engageante et mobilisatrice, stimulant ainsi une action
          collective en faveur de la préservation de notre patrimoine naturel.] texte provisoire
        </p>
      </section>
    </>
  );
}
